# Generated by Django 4.1 on 2022-08-13 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0009_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='Job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='Job.job'),
            preserve_default=False,
        ),
    ]
