# Generated by Django 4.1 on 2022-08-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0010_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
